name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^3.1.2
  crystal_navigation_bar: ^1.0.4
  iconly: ^1.0.1
  introduction_screen: ^3.1.17
  lottie: ^3.3.1
  intl: ^0.18.0  # ✅ Required for DateFormat
  firebase_core: ^3.13.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_crashlytics: ^4.3.6
  cached_network_image: ^3.4.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  supabase_flutter: ^2.9.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  syncfusion_flutter_gauges: ^29.2.10
  share_plus: ^11.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:   
    - assets/animations/
    - assets/images/

