name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^3.1.2
  crystal_navigation_bar: ^1.0.4
  iconly: ^1.0.1
  introduction_screen: ^3.1.17
  lottie: ^3.3.1
  intl: ^0.18.0  # ✅ Required for DateFormat

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:   
    - assets/animations/
    - assets/images/

